# requirements.yml
---
collections:
  - name: community.proxmox
    version: 1.3.0

  - name: community.grafana
    version: 2.3.0

  - name: community.docker
    version: 4.6.0

  - name: community.hashi_vault
    version: 7.0.0

  - name: community.general
    version: 11.2.1