# fashomelab/roles/portainer_agent/main.yml
---
- name: Pull Portainer_Agent image
  community.docker.docker_image:
    name: portainer/agent:{{ portainer_agent_version }}
    source: pull

- name: Run Portainer_Agent container
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:{{ portainer_agent_version }}
    ports:
      - "9001:9001"
    restart_policy: always
    state: started
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
