---
- name: Pull Node Exporter image
  community.docker.docker_image:
    name: prom/node-exporter:{{ node_exporter_version }}
    source: pull
  register: node_exporter_image
  notify: Restart node_exporter container

- name: Verify Node Exporter is accessible
  ansible.builtin.uri:
    url: "http://{{ ansible_host | default('localhost') }}:9100/metrics"
    status_code: 200
    timeout: 30
  register: node_exporter_health
  retries: 3
  delay: 5
  until: node_exporter_health.status == 200
