# fashomelab/roles/prometheus/tasks/main.yml
---
- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: nobody
    group: nogroup
    mode: '0755'

- name: Create Prometheus configuration directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: nobody
    group: nogroup
    mode: '0755'

- name: Template Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: nobody
    group: nogroup
    mode: '0644'

- name: Create Docker network for monitoring
  community.docker.docker_network:
    name: monitoring
    state: present

- name: Create Docker volume for Prometheus data
  community.docker.docker_volume:
    name: prometheus_data
    state: present
    driver: local

- name: Pull Prometheus Docker image
  community.docker.docker_image:
    name: "prom/prometheus:{{ prometheus_version }}"
    source: pull
    state: present

- name: Run Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: "prom/prometheus:{{ prometheus_version }}"
    state: started
    restart_policy: always
    network_mode: monitoring
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.enable-lifecycle
    user: nobody
    log_driver: json-file
    log_opt:
      max-size: "10m"
      max-file: "3"

- name: Verify Prometheus is accessible
  ansible.builtin.uri:
    url: "http://{{ ansible_host | default('localhost') }}:9090/graph"
    status_code: 200
    timeout: 30
  register: prometheus_health
  retries: 3
  delay: 5
  until: prometheus_health.status == 200
