---
name: Ansible CI - FasHomelab

on:
  # Run on every push to the 'develop' branch for continuous validation
  push:
    branches:
      - develop
    paths:
      - 'inventory/**'
      - 'playbooks/**'
      - 'roles/**'
      - '.github/workflows/ansible-homelab-ci.yaml'

  # Run as a gatekeeper on Pull Requests targeting the 'main' branch
  pull_request:
    branches:
      - main
    paths:
      - 'inventory/**'
      - 'playbooks/**'
      - 'roles/**'
      - '.github/workflows/ansible-homelab-ci.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-lint:
    name: Validate and Lint Ansible (develop)
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ${{ github.workspace }}/ansible.cfg
      ANSIBLE_HOST_KEY_CHECKING: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Ansible and Pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.ansible/collections
          key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.txt', '**/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - name: Create and activate venv
        run: python3 -m venv venv

      - name: Install Ansible Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: |
          source venv/bin/activate
          ansible-lint .

      - name: Run Ansible Syntax Check
        run: |
          source venv/bin/activate
          ansible-playbook playbooks/site.yml -i inventory/ci/ --syntax-check

      - name: Clean up .vault directory
        if: always()
        run: rm -rf /home/runner/.vault

      - name: Test Vault Connectivity
        run: curl -sfI $VAULT_ADDR/v1/sys/health
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

      - name: Import Proxmox & Ansible Secrets from Vault
        id: vault_secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: fashomelab-ansible-role
          method: jwt
          jwtGithubAudience: https://token.actions.githubusercontent.com
          secrets: |
            kv/data/homelab/proxmox-credentials PROXMOX_API_USER | PROXMOX_USER ;
            kv/data/homelab/proxmox-credentials PROXMOX_API_TOKEN_ID | PROXMOX_TOKEN_ID ; 
            # Add additional secrets as needed
          exportEnv: true
          exportToken: true
          outputToken: true
          tlsSkipVerify: false
          jwtTtl: 3600
          ignoreNotFound: false

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.CI_ANSIBLE_PRIVATE_KEY }}

      - name: Run Ansible Playbook in Check Mode (Dry Run)
        env:
          ANSIBLE_REMOTE_USER: ${{ env.ANSIBLE_USER }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ steps.vault_secrets.outputs.vault_token }}
          ANSIBLE_HASHI_VAULT_VERBOSE: 1
        run: |
          source venv/bin/activate
          ansible-playbook playbooks/site.yml -i inventory/fashomelab/ --check -v